version: '3'
services:
  caffeinebot:
    build:
      context: .
      image: croncorp/python-ffmpeg:latest
    volumes:
      - ./files:/files
      - ./cogs:/cogs
    env_file:
      - .env
    command: ["python", "main.py"]
